nome = input('Qual o seu nome, belezinha?')
dia = input('E que dia do mês você nasceu?')
mes = input('De qual mês?')
ano = input('E qual foi o ano da sua estréia no planeta Terra?')
cor = input('Qual a sua cor preferida?')
signo = input('Qual o seu signo?')
comida = input('Qual a sua comida favorita?')
filme = input('Qual o seu filme preferido?')
print ('Olá', nome, '! Já sei que você nasceu em',dia,'/', mes, '/', ano, ', sua cor preferida é', cor, ', seu signo é ', signo, 'sua comida favorita é ', comida, 'e seu filme favorito é', filme) 
